version: "3.9"

services:
  db-init:
    image: postgres:17
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /var/lib/postgresql/socket
        tmpfs:
          mode: 1777
      - type: tmpfs
        target: /var/lib/postgresql/tmp
        tmpfs:
          mode: 1777
    entrypoint:
      - sh
      - -c
      - |
        mkdir -p /var/lib/postgresql/socket /var/lib/postgresql/tmp
        chown -R 2000:2000 /var/lib/postgresql/data
        # Setting permissions (ignore errors if they occur)
        chmod 1777 /var/lib/postgresql/socket /var/lib/postgresql/tmp || true

  db:
    image: postgres:17
    user: "2000:2000"
    shm_size: 256m
    restart: always
    container_name: "db"
    command:
      [
        "postgres",
        "-c",
        "max_connections=200",
        "-c",
        "client_connection_check_interval=60000",
        "-c",
        "unix_socket_directories=/var/lib/postgresql/socket",
      ]
    environment:
      POSTGRES_DB: "blockscout"
      POSTGRES_USER: "blockscout"
      POSTGRES_PASSWORD: "ceWb1MeLBEeOIfk65gU8EjF8"
      TMPDIR: "/var/lib/postgresql/tmp"
    ports:
      - target: 5432
        published: 7432
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /var/lib/postgresql/socket
        tmpfs:
          mode: 1777
      - type: tmpfs
        target: /var/lib/postgresql/tmp
        tmpfs:
          mode: 1777
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockscout -d blockscout"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
