version: "3.9"

networks:
  igra-l2-network:
    external: true

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    networks:
      - igra-l2-network

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init
    networks:
      - igra-l2-network

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
    networks:
      - igra-l2-network

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend

    links:
      - db:database
    environment:
      ETHEREUM_JSONRPC_VARIANT: "geth"
      ETHEREUM_JSONRPC_URL: "http://igra-dev-el:8545"
      ETHEREUM_JSONRPC_WS_URL: "ws://igra-dev-el:8546"
      ETHEREUM_JSONRPC_HTTP_URL: "http://igra-dev-el:8545"
      ETHEREUM_JSONRPC_TRACE_URL: "http://igra-dev-el:8545"
      ETHEREUM_JSONRPC_TRANSPORT: "http"
      CHAIN_ID: "2600"
      ENABLE_WEBSOCKET_CONTROLLER: "true"
      SOCKET_ROOT: "/"
      CHAIN_SPEC_PATH: "" # Set to empty to skip genesis.json requirement
      DISABLE_INDEXER: "false"
      DISABLE_REALTIME_INDEXER: "false"
    networks:
      - igra-l2-network

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    networks:
      - igra-l2-network

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    networks:
      - igra-l2-network

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend

    environment:
      NEXT_PUBLIC_NETWORK_ID: "2600"
      NEXT_PUBLIC_NETWORK_RPC_URL: "http://igra-dev-el:8545"
      HOST: "0.0.0.0"
    networks:
      - igra-l2-network

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init
    networks:
      - igra-l2-network

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db
    networks:
      - igra-l2-network

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats
    networks:
      - igra-l2-network

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    networks:
      - igra-l2-network

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
    networks:
      igra-l2-network:
        aliases:
          - proxy
